version: "3.9"
services:
  web:
    build: .
    ports:
      - "56733:80"
    volumes:
      - .:/app
  test:
    build:
      context: .
      dockerfile: .ci/Dockerfile
    command: python -m pytest
